#!/bin/bash -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

export VAULT_TOKEN=$(echo $RANDOM | md5sum | head -c 20; echo;)

function general_envs() {
  [ -z "$BROKER_ID" ] && ( echo "BROKER_ID not set!"; exit 1)
  [ -z "$VAULT" ] && ( echo "Vault address VAULT not set!"; exit 1)
  export BROKER_ID
  export BROKER_URL="https://${BROKER_ID}"
}

function dev_envs() {
  [ -z "$PROXY1_ID" ] && ( echo "PROXY1_ID not set!"; exit 1)
  [ -z "$PROXY2_ID" ] && ( echo "PROXY2_ID not set!"; exit 1)
  export PROXY1_ID
  export PROXY2_ID
  export APP_ID_SHORT=${APP_ID_SHORT:-connect}
  export APP_KEY=${APP_KEY:-ConnectSecret}
  export PROXY1_ID_SHORT=$(echo $PROXY1_ID | cut -d '.' -f 1)
  export PROXY2_ID_SHORT=$(echo $PROXY2_ID | cut -d '.' -f 1)
  export BROKER_ID=$(echo $PROXY1_ID | cut -d '.' -f 2-)
}

function local_envs() {
  [ -z "$PROXY_ID" ] && ( echo "PROXY_ID not set!"; exit 1)
  export PROXY_ID
  export APP_ID_SHORT=${APP_ID_SHORT:-connect}
  export APP_KEY=${APP_KEY:-ConnectSecret}
  export PROXY_ID_SHORT=$(echo $PROXY_ID | cut -d '.' -f 1)
  export BROKER_ID=$(echo $PROXY_ID | cut -d '.' -f 2-)
}

function clean() {
  case "$1" in
    dev)
      docker_compose_file="docker-compose-dev.yml"
    ;;
    central)
      docker_compose_file="docker-compose-central.yml"
    ;;
    local)
      docker_compose_file="docker-compose-local.yml"
    ;;
  esac
  docker-compose -f $docker_compose_file down
  rm -vf pki/*.pem pki/*.json
}

case "$1" in
  start_dev)
    general_envs
    dev_envs
    clean dev
    echo "$VAULT_TOKEN" > ./pki/pki.secret
    pki/pki.sh devsetup
    docker-compose -f docker-compose-dev.yml up --abort-on-container-exit
    ;;
  start_central)
    general_envs
    clean central
    echo "$VAULT_TOKEN" > ./pki/pki.secret
    pki/pki.sh setup_central
    docker-compose -f docker-compose-central.yml up --abort-on-container-exit
    ;;
  start_local)
    general_envs
    local_envs
    docker-compose -f docker-compose-local.yml up --abort-on-container-exit
    ;;
  clean)
    clean $2
    ;;
  stop)
    clean $2
    ;;
  *)
    echo "Usage: $0 start_dev|start_central|start_local|stop|clean"
    ;;
esac
