version: "3.7"
networks:
  traefik:
    external: true
services:
  vault:
    image: vault
    ports:
      - "8201:8200"
    volumes:
      - ./pki:/pki
      - ./pki-data:/vault/file
      - ./config.hcl:/vault/config/config.hcl:ro
    # Enables production mode!
    command: server
    cap_add:
      - IPC_LOCK
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.frontend.rule=Host:ca.dev.ccp-it.dktk.dkfz.de"
    # # - "traefik.http.routers.beam-vault.rule=Host(`vault.demo.beam.samply.de`)" v2
    # networks:
    #   - default
    #   - traefik
    restart: always
  broker:
    depends_on: [vault]
    image: samply/beam-broker:develop
    ports:
      - 8084:8080
    environment:
      RUST_LOG: debug
      BROKER_URL: ${BROKER_URL}
      PKI_ADDRESS: http://vault:8200
      no_proxy: vault
      NO_PROXY: vault
      PRIVKEY_FILE: /run/secrets/dummy.pem
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:broker.dev.ccp-it.dktk.dkfz.de"
#      - "traefik.http.routers.beam-vault.rule=Host(`vault.demo.beam.samply.de`)" v2
    networks:
      - default
      - traefik
    secrets:
      - pki.secret
      - dummy.pem
#  shell:
#    image: ubuntu
#    environment:
#      BROKER_URL: https://broker.demo.beam.samply.de
#      PROXY1_ID: ${PROXY1_ID}
#      PROXY2_ID: ${PROXY2_ID}
#      PKI_ADDRESS: http://vault:8200
#    secrets:
#      - pki.secret
#      - privkey.pem
#    command: sh -c export
secrets:
  pki.secret:
    file: ./pki/pki.secret
  dummy.pem:
    file: ./pki/dummy.priv.pem
