version: "3.7"
services:
  vault:
    image: vault
    ports:
      - 127.0.0.1:8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - ./pki:/pki
    networks:
      - default
  broker:
    depends_on: [vault]
    image: samply/beam-broker:develop
    ports:
      - 8081:8080
    environment:
      BROKER_URL: ${BROKER_URL}
      PKI_ADDRESS: http://vault:8200
      no_proxy: vault
      NO_PROXY: vault
      PRIVKEY_FILE: /run/secrets/dummy.pem
    networks:
      - default
    secrets:
      - pki.secret
      - dummy.pem
#  shell:
#    image: ubuntu
#    environment:
#      BROKER_URL: https://broker.demo.beam.samply.de
#      PROXY1_ID: ${PROXY1_ID}
#      PROXY2_ID: ${PROXY2_ID}
#      PKI_ADDRESS: http://vault:8200
#    secrets:
#      - pki.secret
#      - privkey.pem
#    command: sh -c export
secrets:
  pki.secret:
    file: ./pki/pki.secret
  dummy.pem:
    file: ./pki/dummy.priv.pem
