version: "3.7"
networks:
  traefik:
    external: true
services:
  vault:
    image: vault
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - ./pki:/pki
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:vault.demo.beam.samply.de"
    networks:
      - traefik
      - default
  broker:
    image: samply/beam-broker:develop
    ports:
      - 8080:8080
    environment:
      BROKER_URL: ${BROKER_URL}
      PKI_ADDRESS: http://vault:8200
      no_proxy: vault
      NO_PROXY: vault
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${BROKER_ID}"
    networks:
      - traefik
      - default
    secrets:
      - pki.secret
  proxy1:
    image: samply/beam-proxy:develop
    ports:
      - 8081:8081
    environment:
      BROKER_URL: ${BROKER_URL}
      PROXY_ID: ${PROXY_ID}
      PKI_ADDRESS: http://vault:8200
      APP_0_ID: ${APP_ID_SHORT}
      APP_0_KEY: ${APP_KEY}
      no_proxy: vault
      NO_PROXY: vault
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${PROXY_ID}"
    networks:
      - traefik
      - default
    secrets:
      - pki.secret
      - privkey.pem
#  shell:
#    image: ubuntu
#    environment:
#      BROKER_URL: https://broker.demo.beam.samply.de
#      PROXY_ID: proxy1.broker.demo.beam.samply.de
#      PKI_ADDRESS: http://vault:8200
#      APPKEY_app1: ApiKey1
#    secrets:
#      - pki.secret
#      - privkey.pem
#    command: sh -c export
secrets:
  pki.secret:
    file: ./pki.secret
  privkey.pem:
    file: ./pki/${PROXY_ID_SHORT}.priv.pem
