version: "3.7"
services:
  vault:
    image: vault
    ports:
      - 127.0.0.1:8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - ./pki:/pki
    networks:
      - default
  broker:
    depends_on: [vault]
    image: samply/beam-broker:develop
    ports:
      - 8081:8080
    environment:
      BROKER_URL: ${BROKER_URL}
      PKI_ADDRESS: http://vault:8200
      no_proxy: vault
      NO_PROXY: vault
      PRIVKEY_FILE: /run/secrets/dummy.pem
    networks:
      - default
    secrets:
      - pki.secret
      - dummy.pem
  proxy1:
    depends_on: [broker]
    image: samply/beam-proxy:develop
    ports:
      - 8082:8081
    environment:
      BROKER_URL: ${BROKER_URL}
      PROXY_ID: ${PROXY1_ID}
      APP_0_ID: ${APP_ID_SHORT}
      APP_0_KEY: ${APP_KEY}
      PRIVKEY_FILE: /run/secrets/proxy1.pem
    networks:
      - default
    secrets:
      - proxy1.pem
  proxy2:
    depends_on: [broker]
    image: samply/beam-proxy:develop
    ports:
      - 8083:8081
    environment:
      BROKER_URL: ${BROKER_URL}
      PROXY_ID: ${PROXY2_ID}
      APP_0_ID: ${APP_ID_SHORT}
      APP_0_KEY: ${APP_KEY}
      PRIVKEY_FILE: /run/secrets/proxy2.pem
      VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - default
    secrets:
      - proxy2.pem
#  shell:
#    image: ubuntu
#    environment:
#      BROKER_URL: https://broker.demo.beam.samply.de
#      PROXY1_ID: ${PROXY1_ID}
#      PROXY2_ID: ${PROXY2_ID}
#      PKI_ADDRESS: http://vault:8200
#    secrets:
#      - pki.secret
#      - privkey.pem
#    command: sh -c export
secrets:
  pki.secret:
    file: ./pki/pki.secret
  proxy1.pem:
    file: ./pki/${PROXY1_ID_SHORT}.priv.pem
  proxy2.pem:
    file: ./pki/${PROXY2_ID_SHORT}.priv.pem
  dummy.pem:
    file: ./pki/dummy.priv.pem
