version: "3.7"
services:
  proxy:
    image: samply/beam-proxy:develop
    ports:
      - 8082:8081
    environment:
      BROKER_URL: ${BROKER_URL}
      PROXY_ID: ${PROXY_ID}
      PKI_ADDRESS: ${VAULT}
      APP_0_ID: ${APP_ID_SHORT}
      APP_0_KEY: ${APP_KEY}
      PRIVKEY_FILE: /run/secrets/proxy.pem
      ALL_PROXY: ${http_proxy}
      HTTP_PROXY: ${http_proxy}
      HTTPS_PROXY: ${https_proxy}
      NO_PROXY: ${no_proxy}
    networks:
      - default
    secrets:
      - pki.secret
      - proxy.pem
  connect:
    depends_on: [proxy]
    image: samply/beam-connect:main
    ports:
      - 8062:8062
    environment:
      PROXY_URL: http://proxy:8081
      PROXY_APIKEY: ${APP_KEY}
      APP_ID: ${APP_ID_SHORT}.${PROXY_ID}
      DISCOVERY_URL: ${DISCOVERY_URL}
      LOCAL_TARGETS_FILE: /run/secrets/connect_targets.json
      ALL_PROXY: ${http_proxy}
      HTTP_PROXY: ${http_proxy}
      HTTPS_PROXY: ${https_proxy}
      NO_PROXY: proxy
    networks:
      - default
    secrets:
      - connect_targets.json
#  shell:
#    image: ubuntu
#    environment:
#      BROKER_URL: https://broker.demo.beam.samply.de
#      PROXY1_ID: ${PROXY1_ID}
#      PROXY2_ID: ${PROXY2_ID}
#      PKI_ADDRESS: http://vault:8200
#    secrets:
#      - pki.secret
#      - privkey.pem
#    command: sh -c export
secrets:
  pki.secret:
    file: ./pki/pki.secret
  proxy.pem:
    file: ./pki/${PROXY_ID_SHORT}.priv.pem
  connect_targets.json:
    file: ./example_targets.json
