version: "3.7"
networks:
  traefik:
    external: true
services:
  vault:
    image: vault
    ports:
      - "127.0.0.1:8201:8200"
    volumes:
      - ./pki:/pki
      - ./pki-data:/vault/file
      - ./config.hcl:/vault/config/config.hcl:ro
    # Enables production mode!
    command: server
    cap_add:
      - IPC_LOCK
    restart: always
  broker:
    depends_on: [vault]
    image: samply/beam-broker:develop
    environment:
      BROKER_URL: ${BROKER_URL}
      PKI_ADDRESS: http://vault:8200
      no_proxy: vault
      NO_PROXY: vault
      PRIVKEY_FILE: /run/secrets/dummy.pem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.broker.entrypoints=websecure"
      - "traefik.http.routers.broker.rule=(Host(`broker.bbmri.samply.de`))"
      - "traefik.http.routers.broker.tls=true"
      - "traefik.http.routers.broker.tls.certresolver=letsencrypt"
      - "traefik.http.routers.broker.service=broker"
      - "traefik.http.services.broker.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"
    networks:
      - default
      - traefik
    secrets:
      - pki.secret
      - dummy.pem
      - root.crt
secrets:
  pki.secret:
    file: ./pki/pki.secret
  dummy.pem:
    file: ./pki/dummy.priv.pem
  root.crt:
    file: ./pki/root.crt
