#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

BASE_DIR=$( cd "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. && pwd)
VAULT_TOKEN=$(cat $BASE_DIR/pki/pki.secret)

exec docker run --rm -ti --env-file .env -e VAULT_TOKEN=$VAULT_TOKEN --net=host samply/managepki $@
